== Validate the environment

____
For this scenario, the `+container-tools+` package group, which contains
podman and its depenencies, has already been installed on the system.
____

The feature we will be working with is specific to Podman version 4 and
newer, so first let’s check that podman 4.0.x or newer is installed on
the system.

[source,bash,run,subs=attributes+]
----
podman --version
----

You should see output similar to this:
[source,text]
----
podman version 5.4.0
----

== Introduction to Podman Pods

A pod within podman is a way of grouping containers that make up
services. We can create a pod easily, with the following command.

[source,bash,run,subs=attributes+]
----
podman pod create --name my-pod
----

You should see output similar to this:
[source,text]
----
[rhel@rhel ~]$ podman pod create --name my-pod
9abe9e47a2a4eda4fa9bd5c329acf0187d91f9ff0c16ab49d1ceb173c8e84cc8
[rhel@rhel ~]$ 
----

Now we can create a container within that pod simply by tellig podman
what pod to create the container in.

[source,bash,run,subs=attributes+]
----
podman run --pod my-pod -d --name my-httpd httpd
----

Again, you should see output similar to this:
[source,text]
----
[rhel@rhel ~]$ podman run --pod my-pod -d --name my-httpd httpd
04446f8062d6bea945b6b6a23743203f7629bf8d1cf7be15def1dbafe984c401
[rhel@rhel ~]$ 
----

Now, we can see that our container is running with

[source,bash,run,subs=attributes+]
----
podman ps
----
[source,text]
----
[rhel@rhel ~]$ podman ps
CONTAINER ID  IMAGE                                    COMMAND           CREATED             STATUS             PORTS       NAMES
672a12919c13  localhost/podman-pause:5.4.0-1750809600                    5 minutes ago       Up About a minute              9abe9e47a2a4-infra
04446f8062d6  docker.io/library/httpd:latest           httpd-foreground  About a minute ago  Up About a minute  80/tcp      my-httpd
[rhel@rhel ~]$
----

But what is that extra container? `+9abe9e47a2a4-infra+`

That is a special container that runs our pod. We can see that the pod
is up and running, with two containers, even though we only started a
single container inside of it.

[source,bash,run,subs=attributes+]
----
podman pod ps
----
[source,text]
----
[rhel@rhel ~]$ podman pod ps
POD ID        NAME        STATUS      CREATED        INFRA ID      # OF CONTAINERS
9abe9e47a2a4  my-pod      Running     6 minutes ago  672a12919c13  2
[rhel@rhel ~]$ 
----

In the next step, we’ll work with networking within our pod.
