== Validate the environment

____
For this scenario, the `+container-tools+` package group, which contains
podman and its depenencies, has already been installed on the system.
____

The feature we will be working with is specific to Podman version 4 and
newer, so first let’s check that podman 4.0.x or newer is installed on
the system.

[source,bash,run]
----
podman --version
----

You should see output similar to this:

== Introduction to Podman Pods

A pod within podman is a way of grouping containers that make up
services. We can create a pod easily, with the following command.

[source,bash,run]
----
podman pod create --name my-pod
----

You should see output similar to this:

Now we can create a container within that pod simply by tellig podman
what pod to create the container in.

[source,bash,run]
----
podman run --pod my-pod -d --name my-httpd httpd
----

Again, you should see output similar to this:

Now, we can see that our container is running with

[source,bash,run]
----
podman ps
----

But what is that extra container? `+2d95aa4fdaee-infra+`

That is a special container that runs our pod. We can see that the pod
is up and running, with two containers, even though we only started a
single container inside of it.

[source,bash,run]
----
podman pod ps
----

In the next step, we’ll work with networking within our pod.
